# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8080/projeto/api/pagamentos
Accept: application/json
###
GET http://localhost:8080/projeto/api/pagamentos/1
Accept: application/json
###
###
POST http://localhost:8080/projeto/api/pagamentos
Content-Type: application/json

{
  "dataLancamento": "2019-12-28T16:52:21.487Z[UTC]",
  "estado": "PAGO",
  "id": 2,
  "precoFinal": 99.99,
  "quantidade": 2,
  "produtoID" : 1 ,
  "username": "socio1"
}
###

###
PUT http://localhost:8080/projeto/api/pagamentos/1
Content-Type: application/json

{
  "dataLancamento": "2019-12-28T16:52:21.487Z[UTC]",
  "estado": "PAGO",
  "precoFinal": 1009.99,
  "quantidade": 33,
  "produtoID" : 1 ,
  "username": "socio2"
}

###
DELETE http://localhost:8080/projeto/api/pagamentos/1
Content-Type: application/json
###
